micronaut:
  application:
    name: flight-info-oag-adapter
  server:
    port: 8080
  http:
    services:
      hello:
        url: http://${micronaut.server.host:localhost}:8081/s
        pool:
          enabled: true
  metrics:
    enabled: true
    export:
      statsd:
        enabled: true
        flavor: datadog
        step: PT1M
        host: localhost
        port: 8125

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

---
tracing:
  jaeger:
    enabled: false
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1

---
hystrix:
  stream:
    enabled: false
