@startuml OagAdapter
    skinparam componentArrowColor Black
    ' left to right direction

    !include <tupadr3/common>
    !include <office/Servers/application_server>

    !include <aws/common>
    !include <aws/General/user/user>
    !include <aws/General/AWScloud/AWScloud>
    !include <aws/Compute/AmazonEC2/AmazonEC2>

    OFF_APPLICATION_SERVER(GDS, GDS) #LightBlue
    OFF_APPLICATION_SERVER(OAGFN, OAG Flight\nNotifications API) #LightBlue
    ' OFF_EMAIL(Email, Email)
    USER(user, User)

    AWSCLOUD(MToD, MToD) {
        OFF_APPLICATION_SERVER(Engage, Engage) #LightGreen
        database "Trip Store" as TSS    #LightGreen
        OFF_APPLICATION_SERVER(TA, Trip Import) #LightGreen

        AMAZONEC2(OAGS, OAG Adapter)
        AMAZONEC2(FRS, Flight Registration\nService)

        database "Flight Registration\nDB" as FRSdb

        queue "Trip/Flight\nEvent Queue" as queue #LightGreen
    }

    GDS .l. TA: Booking created/updated
    TA .. FRS: Register trip for notifications
    FRS -r- FRSdb
    FRS ..>> OAGS: <<Scheduled>>\nRegister Flight(s)\nfor notifications
    OAGS ..>> OAGFN: Register flight\nfor notifications
    OAGS <<.. OAGFN: Notification(s)
    OAGS ~u~>> queue: <<Publish>>\nFlight Update event
    queue ~u~>> FRS: <<Listen>>\nFlight & Trip\nUpdate events
    FRS ~>> Engage: Trip Update\nnotification
    TA ~l~ TSS
    Engage ~u~ TSS
    Engage ~l~ user
@enduml
